### PR TITLE
Generic push handler

### PR DESCRIPTION
**Pull request by letorbi**
With some minor changes the push event handler for the old GitLab syntax can be used as an event handler for generic push events.

This PR adds two additional field names for possible repository URL values and weakens the if condition to accept any JSON requests. Due to the latter change the Gitlab CI handler has be moved one place up and is now the third last handler in the elif cascade (right before the generic handler).

If this PR is merged into the main repo, Git-Auto-Deploy will also be able to handle [Gogs](https://gogs.io) webhooks.

### CODE REVIEW

**Comment by alexandernst** [comment]
I reviewed the code and I like it. Simple and clean :+1:

**Comment by alexandernst** [comment]
Anyways, I'm thinking that we might want to actually split the handlers of each service (gitlab, github, etc...) into plugins. Hmm.... should sleep on that idea and get back here to develop it further.

**Comment by letorbi** [comment]
I'm also not sure whether implementing a plugin-interface here would be a good idea or not. I think it only makes sense if it's very lightweight, since just a few lines of code are required to add a new service. Adding 200 lines of code to manage 100 lines of code would be overkill...

**Comment by alexandernst** [comment]
@letorbi Thing is we're starting to write complex if/else statements and users are pushing PR for new services. I really don't want to get to the point of having a 200 lines if/else if/else piece of code trying to guess each request.

I'd rather have a 200 lines plugin manager and 50 lines per service in separate files. That will make code cleaner and easier to refactor.

**Pull request merged**
