### PR TITLE
Now it can listen pull requests and log every event

### PR DESCRIPTION
**Pull request by levabd**
Add continious delivery via Pull request
First of all I try to implement my workflow

workflow

So I add parameters "raw"(branch in which pull request trying to merge), "pullrequestfilter" and "action" (for example I listen "closed")

PS: I can`t debug service in daemon mod, so I add log  too
All features I add to the documentation

### CODE REVIEW

**Comment by olipo186** [comment]
This is a very nice PR!

Using the logging module is a big improvement as well, now we can close issue https://github.com/olipo186/Git-Auto-Deploy/issues/46.

Thanks!

**Comment by alexandernst** [comment]
Haven't had time to review this properly, but may I ask you @levabd to at least revert the indentation change you did in the example conf file? Also, here and there there are some changes that replace tabs with spaces. I'll mark those for you.

**Comment by alexandernst** [comment]
Ah, sorry, no spaces. Just the conf example.

**Comment by levabd** [comment]
I`m sorry @alexandernst. Is indent problem still actual? I have seen that the configuration has been corrected in 1331a34fb18270fbcfada8655d21d0a6a666e02 commit

**Comment by alexandernst** [comment]
@levabd Indeed, already fixed, so nothing to do here.

**Pull request merged**
